version: '3'

services:
  simple-todo-client:
    image: simple-todo-client
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy-node
    ports:
      - 8080:3000
    environment:
      - NODE_ENV=production
      - PROTOCOL_HEADER=x-forwarded-proto
      - HOST_HEADER=x-forwarded-host
      - ORIGIN=http://localhost:8080
      - PORT=8080
      - VITE_SIMPLE_TODO_API="http://simple-todo-api:3000/api"
      - VITE_ORIGIN_API="http://localhost:3000/api"
      - VITE_SIMPLE_API_BASE="http://localhost:8080/api"
