name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Run build
        run: pnpm run build
