on:
  push:
    branches:
      - main
  pull_request:

name: Docker Compose
jobs:
  docker-compose:
    name: Docker Compose Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: 'docker-compose.yml'
          up-flags: '--build'
          down-flags: '--rmi all'
          services: |
            simple-todo-client
